= Protection Profile for Mobile Device Fundamentals

[cols="1,1,1,1,1,1,1,1"]
|===
8+|mobile-device 

| https://github.com/commoncriteria/mobile-device/tree/master[master] 
a| https://commoncriteria.github.io/mobile-device/master/mobile-device-release.html[📄]
a|[link=https://github.com/commoncriteria/mobile-device/blob/gh-pages/master/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/mobile-device/gh-pages/master/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/mobile-device/blob/gh-pages/master/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/mobile-device/gh-pages/master/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/mobile-device/blob/gh-pages/master/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/mobile-device/gh-pages/master/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/mobile-device/blob/gh-pages/master/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/mobile-device/gh-pages/master/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/mobile-device/gh-pages/master/transforms.svg[transforms,150]
a| 
https://commoncriteria.github.io/mobile-device/master/mobile-device-release-linkable.html[mobile-device-release-linkable.html] +
https://commoncriteria.github.io/mobile-device/master/mobile-device-release.html[mobile-device-release.html] +
https://commoncriteria.github.io/mobile-device/master/mobile-device.html[mobile-device.html] +
https://commoncriteria.github.io/mobile-device/master/mobile-device-paged.pdf[mobile-device-paged.pdf] +
| https://github.com/commoncriteria/mobile-device/tree/release-3.3[release-3.3] 
a| https://commoncriteria.github.io/mobile-device/release-3.3/mobile-device-release.html[📄]
a|[link=https://github.com/commoncriteria/mobile-device/blob/gh-pages/release-3.3/ValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/mobile-device/gh-pages/release-3.3/validation.svg[Validation]
a|[link=https://github.com/commoncriteria/mobile-device/blob/gh-pages/release-3.3/SanityChecksOutput.md]
image::https://raw.githubusercontent.com/commoncriteria/mobile-device/gh-pages/release-3.3/warnings.svg[SanityChecks]
a|[link=https://github.com/commoncriteria/mobile-device/blob/gh-pages/release-3.3/SpellCheckReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/mobile-device/gh-pages/release-3.3/spell-badge.svg[SpellCheck]
a|[link=https://github.com/commoncriteria/mobile-device/blob/gh-pages/release-3.3/TDValidationReport.txt]
image::https://raw.githubusercontent.com/commoncriteria/mobile-device/gh-pages/release-3.3/tds.svg[TDs]
a|image::https://raw.githubusercontent.com/commoncriteria/mobile-device/gh-pages/release-3.3/transforms.svg[transforms,150]
a| 
https://commoncriteria.github.io/mobile-device/release-3.3/mobile-device-release-linkable.html[mobile-device-release-linkable.html] +
https://commoncriteria.github.io/mobile-device/release-3.3/mobile-device-release.html[mobile-device-release.html] +
https://commoncriteria.github.io/mobile-device/release-3.3/mobile-device.html[mobile-device.html] +
https://commoncriteria.github.io/mobile-device/release-3.3/mobile-device-paged.pdf[mobile-device-paged.pdf] +
|===


https://github.com/commoncriteria/mobile-device/issues[image:https://img.shields.io/github/issues/commoncriteria/mobile-device.svg?maxAge=2592000[GitHub
issues Open]]

This repository hosts the draft version of the Protection Profile for
Mobile Device Fundamentals based on the
https://commoncriteria.github.io/pp/mobile-device/mobile-device-esr.html[Essential
Security Requirements (ESR)] for this technology class of products. This
repository is used to facilitate collaboration and development on the
draft document. See the link:#Release-Version[release] section if you
are looking for the officially released version for evaluations. A list
of products that have passed evaluation against this Protection Profile
can be found https://www.niap-ccevs.org/Profile/Info.cfm?id=417[here].

=== Draft Version

* https://commoncriteria.github.io/pp/mobile-device/mobile-device-release.html[Protection
Profile for Mobile Device Fundamentals] (html)
* https://commoncriteria.github.io/pp/mobile-device/mobile-device-release.pdf[Protection
Profile for Mobile Device Fundamentals] (pdf)

=== Release Version

* https://www.niap-ccevs.org/Profile/Info.cfm?PPID=455&id=455[Protection
Profile for Mobile Device Fundamentals v3.2]

=== Contributing

If you are interested in contributing directly to future versions the
this Protection Profile, please consider joining the NIAP technical
community. *
https://www.niap-ccevs.org/NIAP_Evolution/tech_communities.cfm[How to
join the NIAP Technical Community (Mailing list and updates)]

=== Feedback

Questions, comments, and fixes can be submitted to the
https://github.com/commoncriteria/mobile-device/issues[repository issue
tracker]

=== Quickstart

To clone this project along with its _transforms_ submodule run:

....
  git clone --recursive git@github.com:commoncriteria/mobile-device.git
....

or

....
  git clone --recursive https://github.com/commoncriteria/mobile-device.git
....

To pull updates from the upstream _transforms_ submodule and commit them
run:

....
 git submodule update --remote transforms &&\
 git add transforms                       &&\
 git commit
....

==== Development Info

https://github.com/commoncriteria/transforms/wiki/Working-with-Transforms-as-a-Submodule[Help
working with Transforms Submodule]

=== Repository Content

* input - Contains the `meat' of the project. It’s the input content (in
XML form) that gets transformed to readable html.
* output - The output directory where the html is placed after
transformation.
* output/images - The directory where images are stored
* transforms - Points to the transform subproject which is really a
repository for resources shared amongst many Common Criteria projects.

=== Links

* https://www.niap-ccevs.org/[National Information Assurance Partnership
(NIAP)]
* https://www.commoncriteriaportal.org/[Common Criteria Portal]
